/**
 * ADR Bridge — extracts locked decisions (D-XX entries) from GSD CONTEXT.md
 * files and writes them as standardized ADR files into the vault.
 *
 * Automates decision capture: eliminates manual copy-paste from GSD discussion
 * to vault ADR files (per INFRA-03).
 */

import { existsSync, readFileSync, readdirSync, writeFileSync, renameSync, mkdirSync } from 'fs';
import { join } from 'path';

// ── extractDecisions ─────────────────────────────────────────────

/**
 * Extract D-XX decision entries from the decisions block of a CONTEXT.md file.
 *
 * Only content between decisions tags is parsed.
 * D-XX patterns outside those tags are intentionally ignored.
 *
 * @param {string} contextContent  Full content of a CONTEXT.md file
 * @returns {{ id: string, text: string }[]}  Array of decision objects
 */
export function extractDecisions(contextContent) {
  // Extract content within <decisions>...</decisions> tags only
  const tagMatch = contextContent.match(/<decisions>([\s\S]*?)<\/decisions>/);
  if (!tagMatch) return [];

  const decisionsBlock = tagMatch[1];

  // Match lines like: - **D-01:** Some text here
  const re = /^- \*\*D-(\d+):\*\* (.+)$/gm;
  const results = [];
  let m;
  while ((m = re.exec(decisionsBlock)) !== null) {
    results.push({ id: `D-${m[1].padStart(2, '0')}`, text: m[2].trim() });
  }
  return results;
}

// ── atomicWrite ──────────────────────────────────────────────────

/**
 * Atomic write via tmp + rename to prevent partial writes.
 */
function atomicWrite(filePath, content) {
  const tmp = filePath + '.tmp';
  writeFileSync(tmp, content);
  renameSync(tmp, filePath);
}

// ── nextAdrNumber ────────────────────────────────────────────────

/**
 * Calculate next ADR number by finding the highest NNNN prefix in existing files.
 * Returns 1 if no existing files match the pattern.
 */
function nextAdrNumber(decisionsDir) {
  if (!existsSync(decisionsDir)) return 1;

  const files = readdirSync(decisionsDir);
  const nums = files
    .map((f) => {
      const match = f.match(/^(\d{4})-/);
      return match ? parseInt(match[1], 10) : 0;
    })
    .filter((n) => n > 0);

  if (nums.length === 0) return 1;
  return Math.max(...nums) + 1;
}

// ── buildAdrContent ──────────────────────────────────────────────

/**
 * Build the ADR markdown content from extracted decisions.
 */
function buildAdrContent({ phaseNumber, phaseName, phaseSlug, decisions, adrNumber }) {
  const date = new Date().toISOString().slice(0, 10);
  const paddedNum = String(adrNumber).padStart(4, '0');
  const decisionIdsYaml = `[${decisions.map((d) => d.id).join(', ')}]`;

  const decisionsSection = decisions
    .map((d) => `### ${d.id}: ${d.text}`)
    .join('\n\n');

  return `# ADR-${paddedNum}: Phase ${phaseNumber} — ${phaseName}

---
source: gsd-bridge
phase: ${phaseNumber}
decision_ids: ${decisionIdsYaml}
---

**Date**: ${date}
**Status**: accepted
**Generated by**: gsd-bridge from .planning/phases/${phaseSlug}/${phaseNumber}-CONTEXT.md

## Context

GSD phase discussion for "${phaseName}" produced ${decisions.length} locked decision${decisions.length !== 1 ? 's' : ''}.
Source: .planning/phases/${phaseSlug}/${phaseNumber}-CONTEXT.md

## Decisions

${decisionsSection}

## Consequences

Decisions captured automatically from GSD discuss-phase. Individual decisions
may be superseded by later phases or manual ADRs.
`;
}

// ── bridgeDecisions ──────────────────────────────────────────────

/**
 * Bridge GSD CONTEXT.md decisions into a vault ADR file.
 *
 * @param {object} args
 * @param {number} args.phaseNumber    Phase number (e.g. 13)
 * @param {string} args.phaseName      Human-readable phase name (e.g. "GSD Infrastructure")
 * @param {string} args.phaseSlug      URL-safe slug (e.g. "gsd-infrastructure")
 * @param {string} args.contextPath    Absolute path to the CONTEXT.md file
 * @param {string|null} args.vaultPath Absolute path to vault root, or null
 * @param {string} args.projectName    Project name (directory under vault/projects/)
 *
 * @returns {{ action: 'created'|'noop'|'skipped', adrPath?: string, decisionCount?: number, reason?: string }}
 */
export function bridgeDecisions({
  phaseNumber,
  phaseName,
  phaseSlug,
  contextPath,
  vaultPath,
  projectName,
} = {}) {
  // Programmer errors — throw
  if (phaseNumber === undefined || phaseNumber === null) {
    throw new Error('bridgeDecisions: phaseNumber is required');
  }
  if (!contextPath) {
    throw new Error('bridgeDecisions: contextPath is required');
  }

  // Path traversal guard on projectName (T-13-01)
  if (projectName && /[/\\]|\.\./.test(projectName)) {
    throw new Error('bridgeDecisions: projectName must not contain path separators or parent refs');
  }

  // Non-fatal: vault not found or doesn't exist
  if (!vaultPath || !existsSync(vaultPath)) {
    return { action: 'skipped', reason: 'no vault found' };
  }

  // Non-fatal: context file doesn't exist
  if (!existsSync(contextPath)) {
    return { action: 'skipped', reason: 'CONTEXT.md file not found' };
  }

  // Read CONTEXT.md and extract decisions
  const contextContent = readFileSync(contextPath, 'utf8');
  const decisions = extractDecisions(contextContent);

  if (decisions.length === 0) {
    return { action: 'skipped', reason: 'no decisions found in CONTEXT.md' };
  }

  // Construct decisions directory path and create if needed
  const decisionsDir = join(vaultPath, 'projects', projectName, 'decisions');
  mkdirSync(decisionsDir, { recursive: true });

  // Idempotency check (D-05): scan for existing ADR from this phase + source
  const existingFiles = readdirSync(decisionsDir).filter((f) => f.endsWith('.md'));
  const phasePattern = new RegExp(`^phase:\\s*${phaseNumber}\\s*$`, 'm');
  for (const file of existingFiles) {
    const filePath = join(decisionsDir, file);
    const content = readFileSync(filePath, 'utf8');
    if (content.includes('source: gsd-bridge') && phasePattern.test(content)) {
      return { action: 'noop' };
    }
  }

  // Calculate next ADR number
  const adrNumber = nextAdrNumber(decisionsDir);
  const slug = phaseSlug || phaseName.toLowerCase().replace(/[\s_]+/g, '-').replace(/[^a-z0-9-]/g, '').replace(/-{2,}/g, '-').replace(/^-|-$/g, '');
  const paddedNum = String(adrNumber).padStart(4, '0');
  const filename = `${paddedNum}-${slug}.md`;
  const adrPath = join(decisionsDir, filename);

  // Build and write ADR file atomically
  const content = buildAdrContent({ phaseNumber, phaseName, phaseSlug: slug, decisions, adrNumber });
  atomicWrite(adrPath, content);

  return { action: 'created', adrPath, decisionCount: decisions.length };
}
